#ifndef BASE_TYPE_H
#define BASE_TYPE_H 1

#define INT_TYPE_BEGIN 0
#define N_INT_TYPE 15
#define N_FLOAT_TYPE  3
#define FLOAT_TYPE_BEGIN ( INT_TYPE_BEGIN + N_INT_TYPE )

#define BUILTIN_BASE_TYPE_END ( FLOAT_TYPE_BEGIN + N_FLOAT_TYPE)

#endif

