/* char_literal.c */
#include "char_literal.h"

void init_char_literal(void)
{
  add_initial(TK_CHAR_LITERAL_BEGIN,CHAR_CLASS_SINGLE_QUOTE);
  // char must have at least one char
  add_intermedia_rev(TK_CHAR_LITERAL_BEGIN,TK_CHAR_LITERAL_PART,CHAR_CLASS_SINGLE_QUOTE_NEWLINE_BACKSLASH);
  add_selfloop_rev(TK_CHAR_LITERAL_PART, CHAR_CLASS_SINGLE_QUOTE_NEWLINE_BACKSLASH);
  add_intermedia(TK_CHAR_LITERAL_PART,TK_CHAR_LITERAL_ESCAPED,CHAR_CLASS_BACKSLASH);
  add_intermedia_rev(TK_CHAR_LITERAL_ESCAPED,TK_CHAR_LITERAL_PART,CHAR_CLASS_NEWLINE);
  add_accepted(TK_CHAR_LITERAL_PART, TK_CHAR_LITERAL_END,CHAR_CLASS_SINGLE_QUOTE);
}
