#include "char_class.h"

bool is_white_space(char ch)
{
  return char_is_in_class(ch, CHAR_CLASS_SPACES);
}

// TODO too much , messy, clear up
char *char_class2string[]=
{
  [CHAR_CLASS_EMPTY]="",

  [CHAR_CLASS_LOWER_CASE]="abcdefghijklmnopqrstuvwxyz",

  [CHAR_CLASS_UPPER_CASE]="ABCDEFGHIJKLMNOPQRSTUVWXYZ",

  [CHAR_CLASS_DEC_DIGITS]="0123456789",

  [CHAR_CLASS_DEC_DIGITS_NON_ZERO]="123456789",

  [CHAR_CLASS_IDENTIFIER_BEGIN]=
    "_""abcdefghijklmnopqrstuvwxyz"
    "ABCDEFGHIJKLMNOPQRSTUVWXYZ",

  [CHAR_CLASS_IDENTIFIER_PART] = CC_IDENTIFIER_BEGIN CC_DEC_PART,
  [CHAR_CLASS_SPACES]=CC_SPACES,
  [CHAR_CLASS_NEWLINE]=CC_NEWLINE,
  [CHAR_CLASS_PUNCTUATION]=CC_PUNCTUATION,
  [CHAR_CLASS_OPERATOR]=CC_OPERATOR,
  [CHAR_CLASS_BACKSLASH]=CC_BACKSLASH,

  [CHAR_CLASS_SEPARATOR] = "(){}[]:;,?" "~!%^&*-+<>=/|" " \t\n\r\f\v",

  [CHAR_CLASS_CHAR_LITERAL]=CC_CHAR_LITERAL,
  [CHAR_CLASS_SINGLE_ESCAPE_NON_ZERO ]=CC_SINGLE_ESCAPE_NON_ZERO ,
  [CHAR_CLASS_SINGLE_ESCAPE]=CC_SINGLE_ESCAPE  ,
  [CHAR_CLASS_HEX_LETTER]=CC_HEX_LETTER ,
  [CHAR_CLASS_HEX_DIGITS]="0123456789abcdefgABCDEFG",
  [CHAR_CLASS_OCT_BEGIN_NOT_ZERO ]=CC_OCT_BEGIN_NOT_ZERO ,
  [CHAR_CLASS_OCT_DIGITS]="01234567",
  [CHAR_CLASS_SINGLE_QUOTE]=CC_SINGLE_QUOTE ,
  [CHAR_CLASS_DOUBLE_QUOTE]=CC_DOUBLE_QUOTE ,
  [CHAR_CLASS_L]=CC_L,
  [CHAR_CLASS_U]=CC_U,
  [CAHR_CLASS_SLASH]="/",
  [CHAR_CLASS_STAR]="*",

  [CHAR_CLASS_TILDE]="~",
  [CHAR_CLASS_EXCLAIM]="!",
  [CHAR_CLASS_PERCENT]="%",
  [CHAR_CLASS_CARET]="^",
  [CHAR_CLASS_AMPERSAND]="&",
  [CHAR_CLASS_VERTICAL_BAR]="|",
  [CHAR_CLASS_POSITIVE]="+",
  [CHAR_CLASS_NEGATIVE]="-",

  [CHAR_CLASS_AMPERSAND_EQUAL]="&=",
  [CHAR_CLASS_VERTICAL_BAR_EQUAL]="|=",
  [CHAR_CLASS_POSITIVE_EQUAL]="+=",
  [CHAR_CLASS_NEGATIVE_EQUAL]="-=",
  [CHAR_CLASS_NEGATIVE_EQUAL_GREATER ]="-=>",


  [CHAR_CLASS_LESS]="<",
  [CHAR_CLASS_GREATER]=">",
  [CHAR_CLASS_LESS_EQUAL]="<=",
  [CHAR_CLASS_GREATER_EQUAL]=">=",
  [CHAR_CLASS_SLASH_STAR_EQUAL]="/*=",
  [CHAR_CLASS_X]="x",
  [CHAR_CLASS_ZERO]="0",
  [CHAR_CLASS_EQUAL]="=",
  [CHAR_CLASS_DOUBLE_QUOTE_NEWLINE_BACKSLASH]="\\\n\r\"",
  [CHAR_CLASS_SINGLE_QUOTE_NEWLINE_BACKSLASH]="\\\n\r\'",
  [CHAR_CLASS_DOUBLE_QUOTE_NEWLINE]="\n\r\"",

  [ CHAR_CLASS_SINGLE_QUOTE_BACKSLASH_NEWLINE ]="\'\\\n\r",
  [ CHAR_CLASS_SINGLE_QUOTE_NEWLINE ]="\'\n\r",
  [ CHAR_CLASS_INT_SUFFIX]="uUlL",
  [ CHAR_CLASS_FLOAT_SUFFIX]="fFlL",

  [CHAR_CLASS_OCT_BEGIN_X_U_L]=CC_OCT_BEGIN CC_L CC_X CC_U,
  [CHAR_CLASS_HEX_BEGIN_U_L]=CC_HEX_BEGIN CC_U CC_L,
  [CHAR_CLASS_OCT_BEGIN_U_L]=CC_OCT_BEGIN CC_U CC_L,
  [CHAR_CLASS_PERIOD]=CC_PERIOD,
  [ CHAR_CLASS_OCT_BEGIN_X_U_L_PERIOD ]=CC_OCT_BEGIN
    CC_L CC_X CC_U CC_PERIOD,

  [ CHAR_CLASS_DEC_PART_PERIOD ]=CC_DEC_PART CC_PERIOD,
  [ CHAR_CLASS_DEC_PART_PERIOD_U_L ]=CC_DEC_PART CC_PERIOD CC_U CC_L,
  [ CHAR_CLASS_E ]= CC_E,
  [ CHAR_CLASS_SIGN ]=CC_SIGN,
  [CHAR_CLASS_STAR_SLASH]="*/",
  [ CHAR_CLASS_DOUBLE_QUOTE_SINGLE_QUOTE ]=CC_DOUBLE_QUOTE_SINGLE_QUOTE,
  [ CHAR_CLASS_DEC_PART_E ]=CC_DEC_PART CC_E,
  [ CHAR_CLASS_DEC_PART_E_SIGN ]=CC_DEC_PART CC_SIGN CC_E,
  [ CHAR_CLASS_XX]="xX",
};

int char_is_in_class(entry_t cond, entry_t ch)
{
  assert (CHAR_CLASS_EMPTY <= cond && cond < _CHAR_CLASS_NULL);
  assert (ch); // '\0' does no good

  char *chcl=char_class2string[cond];
  assert (chcl);
  bool in_class = strchr(chcl, ch);
  return in_class;
}
