#include "char_literal.h"

 
void init_char_literal(void)
{
  /* this is always right */
  add_initial(TK_CHAR_LITERAL_BEGIN,CHAR_CLASS_SINGLE_QUOTE);
  add_intermedia_rev(TK_CHAR_LITERAL_BEGIN,TK_CHAR_LITERAL_PART, CHAR_CLASS_SINGLE_QUOTE_BACKSLASH_NEWLINE);
  add_accepted(TK_CHAR_LITERAL_PART, TK_CHAR_LITERAL_END, CHAR_CLASS_SINGLE_QUOTE);

  add_intermedia(TK_CHAR_LITERAL_BEGIN,TK_CHAR_LITERAL_ESCAPED_0,CHAR_CLASS_BACKSLASH);
  add_intermedia(TK_CHAR_LITERAL_ESCAPED_0, TK_CHAR_LITERAL_PART,CHAR_CLASS_SINGLE_QUOTE);
  add_intermedia_rev(TK_CHAR_LITERAL_ESCAPED_0,TK_CHAR_LITERAL_ESCAPED_1, CHAR_CLASS_SINGLE_QUOTE_NEWLINE);
  add_intermedia_rev(TK_CHAR_LITERAL_ESCAPED_1,TK_CHAR_LITERAL_ESCAPED_2, CHAR_CLASS_SINGLE_QUOTE_NEWLINE);
  add_intermedia_rev(TK_CHAR_LITERAL_ESCAPED_2,TK_CHAR_LITERAL_PART, CHAR_CLASS_SINGLE_QUOTE_NEWLINE);
  
  add_accepted(TK_CHAR_LITERAL_ESCAPED_1, TK_CHAR_LITERAL_END, CHAR_CLASS_SINGLE_QUOTE);
  add_accepted(TK_CHAR_LITERAL_ESCAPED_2, TK_CHAR_LITERAL_END, CHAR_CLASS_SINGLE_QUOTE);

}
