#include "state.h"

const char *token_state_tab[]=
{
  
  [TK_INIT]="TK_INIT",
  [TK_IDENTIFIER_BEGIN]="TK_IDENTIFIER_BEGIN",
  [TK_IDENTIFIER_END]="TK_IDENTIFIER_END",
  [TK_ONE_CHAR_BEGIN]="TK_ONE_CHAR_BEGIN",
  [TK_ONE_CHAR_END]="TK_ONE_CHAR_END",

  [TK_INT_DEC_BEGIN]="TK_INT_DEC_BEGIN",
  [TK_INT_HEX_OCT_BEGIN]="TK_INT_HEX_OCT_BEGIN",
  [TK_INT_HEX_BEGIN]="TK_INT_HEX_BEGIN",
  [TK_INT_OCT_BEGIN]="TK_INT_OCT_BEGIN",
  [TK_INT_END]="TK_INT_END",
  [TK_INT_LONG]="TK_INT_LONG",
  [TK_INT_UNSIGNED]="TK_INT_UNSIGNED",
  
  [TK_NULL]="TK_NULL"
};

