#include "tknzr_state.h"
// TODO when tokenizer is
// quite sure to run
// remove this big tab from
// being built
const char *tknzr_state_tab[]=
{

  [TK_INIT]="TK_INIT",
  [TK_IDENTIFIER_BEGIN]="TK_IDENTIFIER_BEGIN",
  [TK_IDENTIFIER_END]="TK_IDENTIFIER_END",

  [TK_INT_HEX_BEGIN]="TK_INT_HEX_BEGIN",
  [TK_INT_OCT_BEGIN]="TK_INT_OCT_BEGIN",
  [TK_INT_END]="TK_INT_END",
  [TK_INT_DEC_BEGIN]="TK_INT_DEC_BEGIN",
  [ TK_INT_SUFFIX_0 ]="TK_INT_SUFFIX_0",
  [ TK_INT_SUFFIX_1 ]="TK_INT_SUFFIX_1",

  [TK_SINGLE_LINE_COMENT_BEGIN]="TK_SINGLE_LINE_COMENT_BEGIN",
  [TK_SINGLE_LINE_COMENT_END]="TK_SINGLE_LINE_COMENT_END",

  [TK_MULTI_LINE_COMENT_BEGIN]="TK_MULTI_LINE_COMENT_BEGIN",
  [TK_MULTI_LINE_COMENT_END]="TK_MULTI_LINE_COMENT_END",


  [TK_TILDE]="TK_TILDE",
  [TK_TILDE_END]="TK_TILDE_END",
  [TK_EXCLAIM]="TK_EXCLAIM",
  [TK_PERCENT]="TK_PERCENT",
  [TK_CARET]="TK_CARET",
  [TK_AMPERSAND]="TK_AMPERSAND",
  [TK_STAR]="TK_STAR",
  [TK_POSITIVE]="TK_POSITIVE",
  [TK_NEGATIVE]="TK_NEGATIVE",
  [TK_LESS]="TK_LESS",
  [TK_GREATER]="TK_GREATER",
  [TK_EQUAL]="TK_EQUAL",
  [TK_SLASH]="TK_SLASH",
  [TK_VERTICAL_BAR]="TK_VERTICAL_BAR",
  [TK_NEGATIVE_GREATER]="TK_NEGATIVE_GREATER",
  [TK_NEGATIVE_LESS]="TK_NEGATIVE_LESS",

  [TK_EXCLAIM_EQUAL]="TK_EXCLAIM_EQUAL",
  [TK_PERCENT_EQUAL]="TK_PERCENT_EQUAL",
  [TK_CARET_EQUAL]="TK_CARET_EQUAL",
  [TK_AMPERSAND_EQUAL]="TK_AMPERSAND_EQUAL",
  [TK_STAR_EQUAL]="TK_STAR_EQUAL",
  [TK_POSITIVE_EQUAL]="TK_POSITIVE_EQUAL",
  [TK_NEGATIVE_EQUAL]="TK_NEGATIVE_EQUAL",
  [TK_LESS_EQUAL]="TK_LESS_EQUAL",
  [TK_GREATER_EQUAL]="TK_GREATER_EQUAL",
  [TK_EQUAL_EQUAL]="TK_EQUAL_EQUAL",
  [TK_SLASH_EQUAL]="TK_SLASH_EQUAL",
  [TK_VERTICAL_BAR_EQUAL]="TK_VERTICAL_BAR_EQUAL",


  [TK_CHAR_LITERAL_BEGIN]="TK_CHAR_LITERAL_BEGIN",
  [TK_CHAR_LITERAL_PART]="TK_CHAR_LITERAL_PART",
  [TK_CHAR_LITERAL_END]="TK_CHAR_LITERAL_END",
  [TK_CHAR_LITERAL_ESCAPED]="TK_CHAR_LITERAL_ESCAPED",

  [TK_STRING_LITERAL_BEGIN]="TK_STRING_LITERAL_BEGIN",
  [TK_STRING_LITERAL_END]="TK_STRING_LITERAL_END",
  [TK_STRING_LITERAL_ESCAPED]="TK_STRING_LITERAL_ESCAPED",

  [TK_FLOAT_FRACTION]="TK_FLOAT_FRACTION",
  [TK_FLOAT_EXPONENT]="TK_FLOAT_EXPONENT",
  [TK_FLOAT_SIGN]="TK_FLOAT_SIGN",
  [TK_NULL]="TK_NULL"
};


