#include "type_des.h"

static type_des type_description[TYPE_DES_TAB_MAX_LEN];

// do not hard code... find out nice way


static const oper_order oper2order[]=
{
  [ TKT_QUESTION ]=OPMT_TRI10,

  [ TKT_BINARY_OP_ADD ]=OPMT_ADD2,
  [ TKT_BINARY_OP_SUB ]=OPMT_ADD2,
  [ TKT_BINARY_OP_DIV ]=OPMT_MUL1,
  [ TKT_BINARY_OP_MUL ]=OPMT_MUL1,
  [ TKT_BINARY_OP_MOD ]=OPMT_MUL1,

  [TKT_BINARY_OP_MOD_ASSIGN]=OPMT_ASS11  ,
  [TKT_BINARY_OP_ADD_ASSIGN]=OPMT_ASS11,
  [TKT_BINARY_OP_SUB_ASSIGN]=OPMT_ASS11,
  [TKT_BINARY_OP_DIV_ASSIGN]=OPMT_ASS11,
  [TKT_BINARY_OP_MUL_ASSIGN]=OPMT_ASS11,
  [TKT_BINARY_OP_ASSIGN]=OPMT_ASS11,

  [ TKT_BINARY_OP_BIT_AND_ASSIGN ]=OPMT_ASS11,
  [ TKT_BINARY_OP_BIT_OR_ASSIGN ]=OPMT_ASS11,
  [ TKT_BINARY_OP_BIT_XOR_ASSIGN ]=OPMT_ASS11,
  [ TKT_BINARY_OP_BIT_LEFT_SHIFT_ASSIGN ]=OPMT_ASS11,
  [ TKT_BINARY_OP_BIT_RIGHT_SHIFT_ASSIGN ]=OPMT_ASS11,

  [TKT_BINARY_OP_BIT_AND]=OPMT_BWAND4,
  [TKT_BINARY_OP_BIT_OR]=OPMT_BWOR6,
  [TKT_BINARY_OP_BIT_XOR]=OPMT_BWXOR5,
  [TKT_BINARY_OP_BIT_LEFT_SHIFT]=OPMT_BWSHIFT3,
  [TKT_BINARY_OP_BIT_RIGHT_SHIFT]=OPMT_BWSHIFT3,

  [TKT_BINARY_OP_LOGICAL_AND]=OPMT_LGAND8,
  [TKT_BINARY_OP_LOGICAL_OR ]=OPMT_LGOR9,

  [TKT_BINARY_OP_CMP_LESS  ]=OPMT_CMP7,
  [TKT_BINARY_OP_CMP_LESS_EQUAL  ]=OPMT_CMP7,
  [TKT_BINARY_OP_CMP_GREATER  ]=OPMT_CMP7,
  [TKT_BINARY_OP_CMP_GREATER_EQUAL ]=OPMT_CMP7,

  [TKT_BINARY_OP_CMP_EQUAL ]=OPMT_CMP7,
  [TKT_BINARY_OP_CMP_NOT_EQUAL  ]=OPMT_CMP7,


};
