#include "construct.h"
#include "lexer/token_type.h"

#define CTR_CASE_RETURN_1(LABEL, RET) case (LABEL): return (RET)
#define CTR_CASE_RETURN_2(LABEL, COND, RET_1, RET_2)\
case (LABEL): return tag == (COND) ? (RET_1) : (RET_2)

/* int */ 
/* ctr_token_type_to_construct(int tt, int tag) */
/* { */
/*   switch(tt) { */
/*     CTR_CASE_RETURN_1(TK_DOT, OP_DOT_ACCESS); */
/*     CTR_CASE_RETURN_1(TKT_UNARY_OP_ADDRESS, OP_PTR_ACCESS); */
/*       return tag == NODE_TAG_UNARY ? OP_PREF_DEC:OP_POST_DEC; */
/*     case TKT_UNARY_OP_PLUS_PLUS: */
/*       return tag == NODE_TAG_UNARY ? OP_PREF_INC:OP_POST_INC; */
/*     CTR_CASE_RETURN_1(TKT_BINARY_OP_ADD, OP_ADD); */
/*     default: */
/*       return CONSTRUCT_NULL; */
/*   } */
/* } */

  UTILLIB_ETAB_BEGIN(construct)
  UTILLIB_ETAB_ELEM(TYPE_S_CHAR)
  UTILLIB_ETAB_ELEM(TYPE_U_CHAR)
  UTILLIB_ETAB_ELEM(TYPE_S_INT)
  UTILLIB_ETAB_ELEM(TYPE_U_INT)
  UTILLIB_ETAB_ELEM(TYPE_S_SHORT)
  UTILLIB_ETAB_ELEM(TYPE_U_SHORT)
  UTILLIB_ETAB_ELEM(TYPE_S_LONG)
  UTILLIB_ETAB_ELEM(TYPE_U_LONG)
  UTILLIB_ETAB_ELEM(TYPE_S_LL)
  UTILLIB_ETAB_ELEM(TYPE_U_LL)
  UTILLIB_ETAB_ELEM(TYPE_FLOAT)
  UTILLIB_ETAB_ELEM(TYPE_DOUBLE)
  UTILLIB_ETAB_ELEM(TYPE_LDOUBLE)
  UTILLIB_ETAB_ELEM(TYPE_VOID)
  UTILLIB_ETAB_ELEM(TYPE_ENUM)
  UTILLIB_ETAB_ELEM(TYPE_UNION)
  UTILLIB_ETAB_ELEM(TYPE_STRUCT)
  UTILLIB_ETAB_ELEM(STMT_FOR)
  UTILLIB_ETAB_ELEM(STMT_WHILE)
  UTILLIB_ETAB_ELEM(STMT_DO_WHILE)
  UTILLIB_ETAB_ELEM(STMT_SWITCH)
  UTILLIB_ETAB_ELEM(STMT_IF)
  UTILLIB_ETAB_ELEM(STMT_ELSE)
  UTILLIB_ETAB_ELEM(STMT_CASE)
  UTILLIB_ETAB_ELEM(STMT_DEFAULT)
  UTILLIB_ETAB_ELEM(STMT_GOTO)
  UTILLIB_ETAB_ELEM(STMT_RETURN)
  UTILLIB_ETAB_ELEM(STMT_CONTINUE)
  UTILLIB_ETAB_ELEM(STMT_BREAK)
  UTILLIB_ETAB_ELEM(STMT_COMPOUND)
  UTILLIB_ETAB_ELEM(STMT_LABEL)
  UTILLIB_ETAB_ELEM(DECL_FUNCTION)
  UTILLIB_ETAB_ELEM(DECL_EXTERNAL)
  UTILLIB_ETAB_ELEM(OP_INVOKE)
  UTILLIB_ETAB_ELEM(OP_SUBSCRIPT)
  UTILLIB_ETAB_ELEM(OP_PTR_ACCESS)
  UTILLIB_ETAB_ELEM(OP_DOT_ACCESS)
  UTILLIB_ETAB_ELEM(OP_POST_INC)
  UTILLIB_ETAB_ELEM(OP_PREF_INC)
  UTILLIB_ETAB_ELEM(OP_POST_DEC)
  UTILLIB_ETAB_ELEM(OP_PREF_DEC)
  UTILLIB_ETAB_ELEM(OP_SIZEOF_TYPE)
  UTILLIB_ETAB_ELEM(OP_SIZEOF_UNARY)
  UTILLIB_ETAB_ELEM(OP_C_CAST)
  UTILLIB_ETAB_ELEM(OP_ADD)
UTILLIB_ETAB_END(construct)
