#ifndef UTILLIB_ETAB_USE_SWITCH
#define UTILLIB_ETAB_USE_SWITCH
#include "enum.h"
#undef UTILLIB_ETAB_USE_SWITCH
#endif

UTILLIB_ENUM_BEGIN(utillib_except)
  UTILLIB_ENUM_ELEM_INIT(UTILLIB_FILE_NOT_FOUND,-1)
  UTILLIB_ENUM_ELEM_INIT(UTILLIB_EINVAL, -2)
  UTILLIB_ENUM_ELEM_INIT(UTILLIB_ENOMEM, -3)
UTILLIB_ENUM_END(utillib_except)
