/*
   Cmplr Library
   Copyright (C) 2017-2018 Cong Feng <cgsdfc@126.com>

   This program is free software; you can redistribute it and/or modify
   it under the terms of the GNU General Public License as published by
   the Free Software Foundation; either version 2 of the License, or
   (at your option) any later version.

   This program is distributed in the hope that it will be useful,
   but WITHOUT ANY WARRANTY; without even the implied warranty of
   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
   GNU General Public License for more details.

   You should have received a copy of the GNU General Public License
   along with this program; if not, write to the Free Software
   Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA
   02110-1301 USA

*/

/* LL(1) parser table */
/* Generated by Utillib.LL(1). DONNOT EDIT !*/
static int ll1_parser_table[]={
	  -2,    0,    1,    4,    5,    6,    2,   -2,    3,   -2,   -2,   -2, 
	  -2,   -2,   -2,   -2,   -2,   -2,    7,   -2,   -2,   -2,   -2,   -2, 
	  -2,   -2,   -2,   -2,   -2,   -2,   -2,   -2,    8,   -2,   -2,   -2, 
	  -2,   12,   -2,   -2,   -2,   -2,   -2,   -1,   -2,   -2,   -1,   -2, 
	  -2,   -2,   -2,   -2,   -2,   -2,   -2,   -1,   -2,   -2,   14,   -2, 
	  -2,    9,    9,    9,    9,    9,    9,   -2,    9,   -1,   -1,   -2, 
	  -2,   -2,   -2,   -2,   -2,   -2,   -2,   -2,   -2,   -1,   11,   -2, 
};
