#include "scanner/reserved.h"
#include "directive.h"

SCANNER_MATCH_RESERVED_BEGIN(prep_match_directive)

  SCANNER_STR_VAL_PAIR(define, DR_DEFINE)
  SCANNER_STR_VAL_PAIR(undef, DR_UNDEF)
  SCANNER_STR_VAL_PAIR(if, DR_IF)
  SCANNER_STR_VAL_PAIR(ifndef, DR_IFNDEF)
  SCANNER_STR_VAL_PAIR(defined, DR_DEFINED)
  SCANNER_STR_VAL_PAIR(line, DR_LINE)
  SCANNER_STR_VAL_PAIR(error, DR_ERROR)
  SCANNER_STR_VAL_PAIR(include, DR_INCLUDE)
  SCANNER_STR_VAL_PAIR(ifdef, DR_IFDEF)
  SCANNER_STR_VAL_PAIR(assert, DR_ASSERT)
  SCANNER_STR_VAL_PAIR(cpu, DR_CPU)
  SCANNER_STR_VAL_PAIR(elif, DR_ELIF)
  SCANNER_STR_VAL_PAIR(else, DR_ELSE)
  SCANNER_STR_VAL_PAIR(ident, DR_IDENT)
  SCANNER_STR_VAL_PAIR(import, DR_IMPORT)
  SCANNER_STR_VAL_PAIR(include_next, DR_INCLUDE_NEXT)
  SCANNER_STR_VAL_PAIR(machine, DR_MACHINE)
  SCANNER_STR_VAL_PAIR(pragma, DR_PRAGMA)
  SCANNER_STR_VAL_PAIR(system, DR_SYSTEM)
  SCANNER_STR_VAL_PAIR(pragma once, DR_PRAGMA_ONCE)
  SCANNER_STR_VAL_PAIR(unassert, DR_UNASSERT)
  SCANNER_STR_VAL_PAIR(warning, DR_WARNING)

SCANNER_MATCH_RESERVED_END(prep_match_directive)

