#ifndef PREP_PREDEFINED_MACRO_H
#define PREP_PREDEFINED_MACRO_H

#include "utillib/enum.h"

UTILLIB_ENUM_BEGIN(predefined_macro)

    UTILLIB_ENUM_ELEM(PREP_FILE)
    UTILLIB_ENUM_ELEM(PREP_LINE)
    UTILLIB_ENUM_ELEM(PREP_DATE)
    UTILLIB_ENUM_ELEM(PREP_TIME)
    UTILLIB_ENUM_ELEM(PREP_STDC)
    UTILLIB_ENUM_ELEM(PREP_STDC_VERSION)
    UTILLIB_ENUM_ELEM(PREP_GNUC)
    UTILLIB_ENUM_ELEM(PREP_GNUC_MINOR)
    UTILLIB_ENUM_ELEM(PREP_GNUG)
    UTILLIB_ENUM_ELEM(PREP_CPLUS_PLUS)
    UTILLIB_ENUM_ELEM(PREP_STRICT_ANSI)
    UTILLIB_ENUM_ELEM(PREP_BASE_FILE)
    UTILLIB_ENUM_ELEM(PREP_INCLUDE_LEVEL)
    UTILLIB_ENUM_ELEM(PREP_VERSION)
    UTILLIB_ENUM_ELEM(PREP_OPTIMIZE)
    UTILLIB_ENUM_ELEM(PREP_REGISTER_PREFIX)
    UTILLIB_ENUM_ELEM(PREP_USER_LABEL_PREFIX)

    UTILLIB_ENUM_END(predefined_macro)
#endif				// PREP_PREDEFINED_MACRO_H
