#ifndef PREP_PREDEFINED_MACRO_H
#define PREP_PREDEFINED_MACRO_H

#include "utillib/enum.h"

UTILLIB_ENUM_BEGIN(predefined_macro)

UTILLIB_ENUM_ELEM(PD_FILE)
UTILLIB_ENUM_ELEM(PD_LINE)
UTILLIB_ENUM_ELEM(PD_DATE)
UTILLIB_ENUM_ELEM(PD_TIME)
UTILLIB_ENUM_ELEM(PD_STDC)
UTILLIB_ENUM_ELEM(PD_STDC_VERSION)
UTILLIB_ENUM_ELEM(PD_GNUC)
UTILLIB_ENUM_ELEM(PD_GNUC_MINOR)
UTILLIB_ENUM_ELEM(PD_GNUG)
UTILLIB_ENUM_ELEM(PD_CPLUS_PLUS)
UTILLIB_ENUM_ELEM(PD_STRICT_ANSI)
UTILLIB_ENUM_ELEM(PD_BASE_FILE)
UTILLIB_ENUM_ELEM(PD_INCLUDE_LEVEL)
UTILLIB_ENUM_ELEM(PD_VERSION)
UTILLIB_ENUM_ELEM(PD_OPTIMIZE)
UTILLIB_ENUM_ELEM(PD_REGISTER_PREFIX)
UTILLIB_ENUM_ELEM(PD_USER_LABEL_PREFIX)

UTILLIB_ENUM_END(predefined_macro)

#endif // PREP_PREDEFINED_MACRO_H
