#define SYM_IDEN                         1
#define SYM_KW_CONST                     2
#define SYM_SEMI                         3
#define SYM_KW_INT                       4
#define SYM_ADD                          5
#define SYM_INTEGER                      6
#define SYM_MINUS                        7
#define SYM_EQ                           8
#define SYM_COMMA                        9
#define SYM_KW_CHAR                     10
#define SYM_CHAR                        11
#define SYM_KW_VOID                     12
#define SYM_LK                          13
#define SYM_RK                          14
#define SYM_LP                          15
#define SYM_RP                          16
#define SYM_LB                          17
#define SYM_RB                          18
#define SYM_KW_RETURN                   19
#define SYM_KW_FOR                      20
#define SYM_KW_SWITCH                   21
#define SYM_KW_IF                       22
#define SYM_KW_ELSE                     23
#define SYM_STRING                      24
#define SYM_GE                          25
#define SYM_DIV                         26
#define SYM_MUL                         27
#define SYM_DEQ                         28
#define SYM_LE                          29
#define SYM_LT                          30
#define SYM_NE                          31
#define SYM_RIGHT_UNARY                 32
#define SYM_GT                          33
