#define SYM_KW_CONST                     1
#define SYM_SEMI                         2
#define SYM_KW_INT                       3
#define SYM_ADD                          4
#define SYM_INTEGER                      5
#define SYM_MINUS                        6
#define SYM_IDEN                         7
#define SYM_EQ                           8
#define SYM_COMMA                        9
#define SYM_KW_CHAR                     10
#define SYM_CHAR                        11
#define SYM_KW_VOID                     12
#define SYM_LP                          13
#define SYM_RP                          14
#define SYM_LB                          15
#define SYM_RB                          16
#define SYM_LK                          17
#define SYM_RK                          18
#define SYM_KW_RETURN                   19
#define SYM_KW_FOR                      20
#define SYM_KW_SWITCH                   21
#define SYM_KW_CASE                     22
#define SYM_COLON                       23
#define SYM_KW_DEFAULT                  24
#define SYM_KW_IF                       25
#define SYM_KW_ELSE                     26
#define SYM_STRING                      27
#define SYM_GE                          28
#define SYM_DIV                         29
#define SYM_MUL                         30
#define SYM_DEQ                         31
#define SYM_LE                          32
#define SYM_LT                          33
#define SYM_NE                          34
#define SYM_RIGHT_UNARY                 35
#define SYM_GT                          36
