#include "ir.h"

UTILLIB_ETAB_BEGIN(cling_opcode_kind)
UTILLIB_ETAB_ELEM(OP_ADD)
UTILLIB_ETAB_ELEM(OP_SUB)
UTILLIB_ETAB_ELEM(OP_IDX)
UTILLIB_ETAB_ELEM(OP_CAL)
UTILLIB_ETAB_ELEM(OP_DIV)
UTILLIB_ETAB_ELEM(OP_MUL)
UTILLIB_ETAB_END(cling_opcode_kind);


