/*
   Cmplr Library
   Copyright (C) 2017-2018 Cong Feng <cgsdfc@126.com>

   This program is free software; you can redistribute it and/or modify
   it under the terms of the GNU General Public License as published by
   the Free Software Foundation; either version 2 of the License, or
   (at your option) any later version.

   This program is distributed in the hope that it will be useful,
   but WITHOUT ANY WARRANTY; without even the implied warranty of
   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
   GNU General Public License for more details.

   You should have received a copy of the GNU General Public License
   along with this program; if not, write to the Free Software
   Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA
   02110-1301 USA

*/
#include "rules.h"
#include "symbols.h"

UTILLIB_RULE_BEGIN(cling_ll1_rules)

UTILLIB_RULE_ELEM(SYM_ADD_OP, SYM_ADD, SYM_MINUS)
UTILLIB_RULE_ELEM(SYM_MUL_OP, SYM_MUL, SYM_DIV)
UTILLIB_RULE_ELEM(SYM_REL_OP, SYM_LT, SYM_LE, SYM_GT, SYM_GE, SYM_NE, SYM_DEQ)
UTILLIB_RULE_ELEM(SYM_PROGRAM, SYM_CONST_DECL, SYM_VAR_DECL, SYM_FUNC_DECL_LS,
                  SYM_MAIN_DECL)
UTILLIB_RULE_ELEM(SYM_EXPR_, SYM_LP, SYM_EXPR, SYM_RP)
UTILLIB_RULE_ELEM(SYM_CONSTANT, SYM_CHAR)
UTILLIB_RULE_ELEM(SYM_CONSTANT, SYM_INTEGER)
UTILLIB_RULE_ELEM(SYM_CONST_DECL, SYM_KW_CONST, SYM_CONST_DEF, SYM_CONST_DEF_LS,
                  SYM_SEMI, SYM_CONST_DECL)
UTILLIB_RULE_ELEM(SYM_CONST_DEF, SYM_KW_INT, SYM_CONST_DEF_INT,
                  SYM_CONST_DEF_INT_LS)
UTILLIB_RULE_ELEM(SYM_CONST_DEF, SYM_KW_CHAR, SYM_CONST_DEF_CHAR,
                  SYM_CONST_DEF_CHAR_LS)
UTILLIB_RULE_ELEM(SYM_CONST_DEF_INT, SYM_IDEN, SYM_EQ, SYM_INTEGER)
UTILLIB_RULE_ELEM(SYM_CONST_DEF_CHAR, SYM_IDEN, SYM_EQ, SYM_CHAR)
UTILLIB_RULE_ELEM(SYM_DECL_HD, SYM_KW_INT, SYM_IDEN)
UTILLIB_RULE_ELEM(SYM_DECL_HD, SYM_KW_CHAR, SYM_IDEN)
UTILLIB_RULE_ELEM(SYM_DECL_HD, SYM_KW_VOID, SYM_IDEN)
UTILLIB_RULE_ELEM(SYM_VAR_DECL, SYM_VAR_DEF, SYM_VAR_DEF_LS, SYM_SEMI,
                  SYM_VAR_DECL)
UTILLIB_RULE_ELEM(SYM_VAR_DEF, SYM_TYPENAME, SYM_IDEN, SYM_EXTEND)
UTILLIB_RULE_ELEM(SYM_TYPENAME, SYM_KW_INT)
UTILLIB_RULE_ELEM(SYM_TYPENAME, SYM_KW_CHAR)
UTILLIB_RULE_ELEM(SYM_EXTEND, SYM_LK, SYM_UINT, SYM_RK)
UTILLIB_RULE_ELEM(SYM_FUNC_DECL, SYM_DECL_HD, SYM_LP, SYM_NARGS, SYM_RP, SYM_LB,
                  SYM_COMP_STMT, SYM_RB)
UTILLIB_RULE_ELEM(SYM_MAIN_DECL, SYM_KW_VOID, SYM_KW_MAIN, SYM_LB, SYM_RB,
                  SYM_LB, SYM_COMP_STMT, SYM_RB)
UTILLIB_RULE_ELEM(SYM_NARGS, SYM_TYPENAME, SYM_IDEN, SYM_NARGS_LS)
UTILLIB_RULE_ELEM(SYM_STMT, SYM_IF_STMT)
UTILLIB_RULE_ELEM(SYM_STMT, SYM_FOR_STMT)
UTILLIB_RULE_ELEM(SYM_STMT, SYM_SWITCH_STMT)
UTILLIB_RULE_ELEM(SYM_STMT, SYM_PRINTF_STMT, SYM_SEMI)
UTILLIB_RULE_ELEM(SYM_STMT, SYM_SCANF_STMT, SYM_SEMI)
UTILLIB_RULE_ELEM(SYM_STMT, SYM_ASSIGN_STMT, SYM_SEMI)
UTILLIB_RULE_ELEM(SYM_STMT, SYM_RETURN_STMT, SYM_SEMI)
UTILLIB_RULE_ELEM(SYM_STMT, UT_SYM_EPS, SYM_SEMI)
UTILLIB_RULE_ELEM(SYM_STMT, SYM_INVOKE_STMT, SYM_SEMI)
UTILLIB_RULE_ELEM(SYM_STMT, SYM_COMP_STMT)
UTILLIB_RULE_ELEM(SYM_IF_STMT, SYM_KW_IF, SYM_LP, SYM_COND, SYM_STMT,
                  SYM_ELSE_CLAUSE)
UTILLIB_RULE_ELEM(SYM_ELSE_CLAUSE, SYM_KW_ELSE, SYM_STMT)
UTILLIB_RULE_ELEM(SYM_FOR_STMT, SYM_KW_FOR, SYM_LP, SYM_FOR_INIT, SYM_SEMI,
                  SYM_COND, SYM_SEMI, SYM_FOR_STEP, SYM_RP, SYM_STMT)
UTILLIB_RULE_ELEM(SYM_FOR_INIT, SYM_IDEN, SYM_EQ, SYM_EXPR)
UTILLIB_RULE_ELEM(SYM_FOR_STEP, SYM_IDEN, SYM_EQ, SYM_IDEN, SYM_ADD_OP,
                  SYM_UINT)
UTILLIB_RULE_ELEM(SYM_SWITCH_STMT, SYW_KW_SWITCH, SYM_EXPR_, SYM_CASE_CLAUSE,
                  SYM_CASE_CLAUSE_LS, SYM_DEFAULT_CLAUSE, SYM_RB)
UTILLIB_RULE_ELEM(SYM_CASE_CLAUSE, SYM_KW_CASE, SYM_CONSTANT, SYM_COLON,
                  SYM_STMT)
UTILLIB_RULE_ELEM(SYM_DEFAULT_CLAUSE, SYM_KW_DEFAULT, SYM_COLON, SYM_STMT)
UTILLIB_RULE_ELEM(SYM_INVOKE_STMT, SYM_IDEN, SYM_LP, SYM_AARGS, SYM_RP)
UTILLIB_RULE_ELEM(SYM_AARGS, SYM_EXPR, SYM_AARGS_LS)
UTILLIB_RULE_ELEM(SYM_PRINTF_STMT, SYM_KW_PRINTF, SYM_LP, SYM_PRINTF_ARGS,
                  SYM_RP)
UTILLIB_RULE_ELEM(SYM_PRINTF_ARGS, SYM_EXPR)
UTILLIB_RULE_ELEM(SYM_PRINTF_ARGS, SYM_STRING, SYM_PRINTF_ARGS_)
UTILLIB_RULE_ELEM(SYM_PRINTF_ARGS_, SYM_COMMA, SYM_EXPR)
UTILLIB_RULE_ELEM(SYM_SCANF_STMT, SYM_KW_SCANF, SYM_LP, SYM_IDEN, SYM_IDEN_LS,
                  SYM_RP)
UTILLIB_RULE_ELEM(SYM_RETURN_STMT, SYM_KW_RETURN, SYM_EXPR_OPT)
UTILLIB_RULE_ELEM(SYM_EXPR_OPT, SYM_EXPR_)
UTILLIB_RULE_ELEM(SYM_COMP_STMT, SYM_CONST_DECL, SYM_VAR_DECL, SYM_STMT_LS)
UTILLIB_RULE_ELEM(SYM_SIGN, SYM_ADD_OP)
UTILLIB_RULE_ELEM(SYM_EXPR, SYM_SIGN, SYM_TERM, SYM_TERM_LS)
UTILLIB_RULE_ELEM(SYM_TERM, SYM_FACT, SYM_FACT_LS)
UTILLIB_RULE_ELEM(SYM_FACT, SYM_IDEN, SYM_EXTEND)
UTILLIB_RULE_ELEM(SYM_FACT, SYM_UINT)
UTILLIB_RULE_ELEM(SYM_FACT, SYM_LP, SYM_EXPR, SYM_RP)
UTILLIB_RULE_ELEM(SYM_FACT, SYM_INVOKE_STMT)
UTILLIB_RULE_ELEM(SYM_FACT, SYM_CONSTANT)
UTILLIB_RULE_ELEM(SYM_FACT, SYM_STRING)

/* list section */
UTILLIB_RULE_ELEM(SYM_IDEN_LS, SYM_COMMA, SYM_IDEN, SYM_IDEN_LS)
UTILLIB_RULE_ELEM(SYM_AARGS_LS, SYM_COMMA, SYM_AARGS, SYM_AARGS_LS)
UTILLIB_RULE_ELEM(SYM_CASE_CLAUSE_LS, SYM_CASE_CLAUSE, SYM_CASE_CLAUSE_LS)
UTILLIB_RULE_ELEM(SYM_STMT_LS, SYM_STMT, SYM_STMT_LS)
UTILLIB_RULE_ELEM(SYM_NARGS_LS, SYM_COMMA, SYM_NARGS, SYM_NARGS_LS)
UTILLIB_RULE_ELEM(SYM_FUNC_DECL_LS, SYM_FUNC_DECL, SYM_FUNC_DECL_LS)
UTILLIB_RULE_ELEM(SYM_CONST_DEF_INT_LS, SYM_COMMA, SYM_CONST_DEF_INT,
                  SYM_CONST_DEF_INT_LS)
UTILLIB_RULE_ELEM(SYM_CONST_DEF_CHAR_LS, SYM_COMMA, SYM_CONST_DEF_CHAR,
                  SYM_CONST_DEF_CHAR_LS)
UTILLIB_RULE_ELEM(SYM_VAR_DEF_LS, SYM_COMMA, SYM_VAR_DEF, SYM_VAR_DEF_LS)
UTILLIB_RULE_ELEM(SYM_EXPR_LS, SYM_COMMA, SYM_EXPR, SYM_EXPR_LS)
UTILLIB_RULE_ELEM(SYM_TERM_LS, SYM_ADD_OP, SYM_TERM, SYM_TERM_LS)
UTILLIB_RULE_ELEM(SYM_FACT_LS, SYM_MUL_OP, SYM_FACT, SYM_FACT_LS)

/* epsilon section */
UTILLIB_RULE_ELEM(SYM_EXPR_OPT, UT_SYM_EPS)
UTILLIB_RULE_ELEM(SYM_VAR_DEF_LS, UT_SYM_EPS)
UTILLIB_RULE_ELEM(SYM_IDEN_LS, SYM_EXPR_LS)
UTILLIB_RULE_ELEM(SYM_PRINTF_ARGS_, SYM_EXPR_LS)
UTILLIB_RULE_ELEM(SYM_STMT_LS, UT_SYM_EPS)
UTILLIB_RULE_ELEM(SYM_CASE_CLAUSE_LS, UT_SYM_EPS)
UTILLIB_RULE_ELEM(SYM_ELSE_CLAUSE, UT_SYM_EPS)
UTILLIB_RULE_ELEM(SYM_AARGS, UT_SYM_EPS)
UTILLIB_RULE_ELEM(SYM_AARGS_LS, UT_SYM_EPS)
UTILLIB_RULE_ELEM(SYM_NARGS, UT_SYM_EPS)
UTILLIB_RULE_ELEM(SYM_NARGS_LS, UT_SYM_EPS)
UTILLIB_RULE_ELEM(SYM_FUNC_DECL_LS, UT_SYM_EPS)
UTILLIB_RULE_ELEM(SYM_EXTEND, UT_SYM_EPS)
UTILLIB_RULE_ELEM(SYM_VAR_DECL, UT_SYM_EPS)
UTILLIB_RULE_ELEM(SYM_CONST_DECL, UT_SYM_EPS)
UTILLIB_RULE_ELEM(SYM_CONST_DEF_INT_LS, UT_SYM_EPS)
UTILLIB_RULE_ELEM(SYM_CONST_DEF_CHAR_LS, UT_SYM_EPS)
UTILLIB_RULE_ELEM(SYM_EXPR_LS, UT_SYM_EPS)
UTILLIB_RULE_ELEM(SYM_TERM_LS, UT_SYM_EPS)
UTILLIB_RULE_ELEM(SYM_FACT_LS, UT_SYM_EPS)
UTILLIB_RULE_ELEM(SYM_SIGN, UT_SYM_EPS)
/* end */
UTILLIB_RULE_END(cling_ll1_rules);
