/*
   Cmplr Library
   Copyright (C) 2017-2018 Cong Feng <cgsdfc@126.com>

   This program is free software; you can redistribute it and/or modify
   it under the terms of the GNU General Public License as published by
   the Free Software Foundation; either version 2 of the License, or
   (at your option) any later version.

   This program is distributed in the hope that it will be useful,
   but WITHOUT ANY WARRANTY; without even the implied warranty of
   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
   GNU General Public License for more details.

   You should have received a copy of the GNU General Public License
   along with this program; if not, write to the Free Software
   Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA
   02110-1301 USA

*/
#include "rules.h"
#include "symbols.h"

UTILLIB_RULE_BEGIN(pascal_rules)
UTILLIB_RULE_ELEM(SYM_PROGRAM, SYM_SUBPRG, SYM_DOT)
UTILLIB_RULE_ELEM(SYM_SUBPRG, SYM_CONST_DECL, SYM_VAR_DECL, SYM_PROC_DECL, SYM_PROC_DECL_LS,
                  SYM_COMP_STMT)
UTILLIB_RULE_ELEM(SYM_CONST_DECL, SYM_KW_CONST, SYM_CONST_DEF, SYM_CONST_DEF_LS,
                  SYM_SEMI)
UTILLIB_RULE_ELEM(SYM_CONST_DEF, SYM_IDEN, SYM_EQ, SYM_UINT)
UTILLIB_RULE_ELEM(SYM_VAR_DECL, SYM_KW_VAR, SYM_IDEN, SYM_IDEN_LS, SYM_SEMI)
UTILLIB_RULE_ELEM(SYM_PROC_DECL, SYM_PROC_HD, SYM_SUBPRG)
UTILLIB_RULE_ELEM(SYM_PROC_HD, SYM_KW_PROC, SYM_IDEN, SYM_SEMI)
UTILLIB_RULE_ELEM(SYM_STMT, SYM_ASS_STMT)
UTILLIB_RULE_ELEM(SYM_STMT, SYM_COND_STMT)
UTILLIB_RULE_ELEM(SYM_STMT, SYM_LOOP_STMT)
UTILLIB_RULE_ELEM(SYM_STMT, SYM_CALL_STMT)
UTILLIB_RULE_ELEM(SYM_STMT, SYM_COMP_STMT)
UTILLIB_RULE_ELEM(SYM_STMT, SYM_READ_STMT)
UTILLIB_RULE_ELEM(SYM_STMT, SYM_WRITE_STMT)
UTILLIB_RULE_ELEM(SYM_ASS_STMT, SYM_IDEN, SYM_CEQ, SYM_EXPR)
UTILLIB_RULE_ELEM(SYM_EXPR, SYM_SIGN, SYM_TERM, SYM_TERM_LS)
UTILLIB_RULE_ELEM(SYM_TERM, SYM_FACT, SYM_FACT_LS)
UTILLIB_RULE_ELEM(SYM_FACT, SYM_IDEN)
UTILLIB_RULE_ELEM(SYM_FACT, SYM_UINT)
UTILLIB_RULE_ELEM(SYM_FACT, SYM_LP, SYM_EXPR, SYM_RP)
UTILLIB_RULE_ELEM(SYM_ADD_OP, SYM_ADD)
UTILLIB_RULE_ELEM(SYM_ADD_OP, SYM_MINUS)
UTILLIB_RULE_ELEM(SYM_MUL_OP, SYM_MUL)
UTILLIB_RULE_ELEM(SYM_MUL_OP, SYM_DIV)
UTILLIB_RULE_ELEM(SYM_COND, SYM_EXPR, SYM_REL_OP, SYM_EXPR)
UTILLIB_RULE_ELEM(SYM_COND, SYM_KW_ODD, SYM_EXPR)
UTILLIB_RULE_ELEM(SYM_REL_OP, SYM_NE)
UTILLIB_RULE_ELEM(SYM_REL_OP, SYM_EQ)
UTILLIB_RULE_ELEM(SYM_REL_OP, SYM_LT)
UTILLIB_RULE_ELEM(SYM_REL_OP, SYM_LE)
UTILLIB_RULE_ELEM(SYM_REL_OP, SYM_GT)
UTILLIB_RULE_ELEM(SYM_REL_OP, SYM_GE)
UTILLIB_RULE_ELEM(SYM_COND_STMT, SYM_KW_IF, SYM_COND, SYM_KW_THEN, SYM_STMT)
UTILLIB_RULE_ELEM(SYM_LOOP_STMT, SYM_KW_WHILE, SYM_COND, SYM_KW_DO, SYM_STMT)
UTILLIB_RULE_ELEM(SYM_CALL_STMT, SYM_KW_CALL, SYM_IDEN)
UTILLIB_RULE_ELEM(SYM_COMP_STMT, SYM_KW_BEGIN, SYM_STMT, SYM_STMT_LS, SYM_KW_END)
UTILLIB_RULE_ELEM(SYM_READ_STMT, SYM_KW_READ, SYM_LP, SYM_IDEN, SYM_IDEN_LS,
                  SYM_RP)
UTILLIB_RULE_ELEM(SYM_WRITE_STMT, SYM_KW_WRITE, SYM_LP, SYM_EXPR, SYM_EXPR_LS,
                  SYM_RP)

/* Single A := eps */
UTILLIB_RULE_ELEM(SYM_STMT, UT_SYM_EPS)
UTILLIB_RULE_ELEM(SYM_STMT_LS, UT_SYM_EPS)
UTILLIB_RULE_ELEM(SYM_CONST_DEF_LS, UT_SYM_EPS)
UTILLIB_RULE_ELEM(SYM_IDEN_LS, UT_SYM_EPS)
UTILLIB_RULE_ELEM(SYM_CONST_DECL, UT_SYM_EPS)
UTILLIB_RULE_ELEM(SYM_VAR_DECL, UT_SYM_EPS)
UTILLIB_RULE_ELEM(SYM_SIGN, UT_SYM_EPS)
UTILLIB_RULE_ELEM(SYM_PROC_DECL, UT_SYM_EPS)
UTILLIB_RULE_ELEM(SYM_EXPR_LS, UT_SYM_EPS)
UTILLIB_RULE_ELEM(SYM_TERM_LS, UT_SYM_EPS)
UTILLIB_RULE_ELEM(SYM_FACT_LS, UT_SYM_EPS)
UTILLIB_RULE_ELEM(SYM_PROC_DECL_LS, UT_SYM_EPS)

UTILLIB_RULE_ELEM(SYM_SIGN, SYM_ADD)
UTILLIB_RULE_ELEM(SYM_SIGN, SYM_MINUS)

  /* List like rules */
UTILLIB_RULE_ELEM(SYM_STMT_LS, SYM_SEMI, SYM_STMT, SYM_STMT_LS)
UTILLIB_RULE_ELEM(SYM_CONST_DEF_LS, SYM_COMMA, SYM_CONST_DEF, SYM_CONST_DEF_LS)
UTILLIB_RULE_ELEM(SYM_IDEN_LS, SYM_COMMA, SYM_IDEN, SYM_IDEN_LS)
UTILLIB_RULE_ELEM(SYM_EXPR_LS, SYM_COMMA, SYM_EXPR, SYM_EXPR_LS)
UTILLIB_RULE_ELEM(SYM_TERM_LS, SYM_ADD_OP, SYM_TERM, SYM_TERM_LS)
UTILLIB_RULE_ELEM(SYM_FACT_LS, SYM_MUL_OP, SYM_FACT, SYM_FACT_LS)
UTILLIB_RULE_ELEM(SYM_PROC_DECL_LS, SYM_SEMI, SYM_PROC_DECL, SYM_PROC_DECL_LS)

UTILLIB_RULE_END(pascal_rules);

size_t const pascal_firsts[][15]={
  [SYM_PROGRAM]={ 
    SYM_KW_CONST, SYM_KW_VAR, SYM_KW_PROC, 
    SYM_IDEN, SYM_KW_IF, SYM_KW_WHILE, SYM_KW_CALL, SYM_KW_BEGIN,
    SYM_KW_READ, SYM_KW_WRITE, UT_SYM_EPS, 
    UT_SYM_NULL
  },
  [SYM_SUBPRG]={
    SYM_KW_CONST, SYM_KW_VAR, SYM_KW_PROC, 
    SYM_IDEN, SYM_KW_IF, SYM_KW_WHILE, SYM_KW_CALL, SYM_KW_BEGIN,
    SYM_KW_READ, SYM_KW_WRITE, UT_SYM_EPS,
    UT_SYM_NULL
  },
  [SYM_CONST_DECL]={
    SYM_KW_CONST,
    UT_SYM_NULL
  },
  [SYM_CONST_DEF]={
    SYM_IDEN,
    UT_SYM_NULL
  },
  [SYM_VAR_DECL]={
    SYM_KW_VAR,
    UT_SYM_NULL
  },
  [SYM_PROC_DECL]={
    SYM_KW_PROC,
    UT_SYM_NULL
  },
  [SYM_PROC_HD]={
    SYM_KW_PROC,
    UT_SYM_NULL
  },
  [SYM_STMT]={
    SYM_IDEN, SYM_KW_IF, SYM_KW_WHILE, SYM_KW_CALL, SYM_KW_BEGIN,
    SYM_KW_READ, SYM_KW_WRITE, UT_SYM_EPS, 
    UT_SYM_NULL
  },
  [SYM_ASS_STMT]={
    SYM_IDEN,
    UT_SYM_NULL
  },
  [SYM_EXPR]={
    SYM_ADD, SYM_MINUS,
    SYM_IDEN, SYM_UINT,
    SYM_LP,
    UT_SYM_NULL
  },
  [SYM_TERM]={
    SYM_IDEN, SYM_UINT, SYM_LP,
    UT_SYM_NULL
  },
  [SYM_FACT]={
    SYM_IDEN, SYM_UINT, SYM_LP,
    UT_SYM_NULL
  },
  [SYM_ADD_OP]={
    SYM_ADD, SYM_MINUS,
    UT_SYM_NULL
  },
  [SYM_MUL_OP]={
    SYM_MUL, SYM_DIV,
    UT_SYM_NULL,
  },
  [SYM_COND]={
    SYM_KW_ODD, 
    SYM_IDEN, SYM_UINT, SYM_LP,
    UT_SYM_NULL
  },
  [SYM_REL_OP]={
    SYM_NE, SYM_LT, SYM_LE,
    SYM_EQ, SYM_GT, SYM_GE,
    UT_SYM_NULL
  },
  [SYM_COND_STMT]={
    SYM_KW_IF,
    UT_SYM_NULL
  },
  [SYM_LOOP_STMT]={
    SYM_KW_WHILE,
    UT_SYM_NULL
  },
  [SYM_CALL_STMT]={
    SYM_KW_CALL,
    UT_SYM_NULL,
  },
  [SYM_COMP_STMT]={
    SYM_KW_BEGIN,
    UT_SYM_NULL
  },
  [SYM_READ_STMT]={
    SYM_KW_READ,
    UT_SYM_NULL
  },
  [SYM_WRITE_STMT]={
    SYM_KW_WRITE,
    UT_SYM_NULL
  },
};




