/*
   Cmplr Library
   Copyright (C) 2017-2018 Cong Feng <cgsdfc@126.com>

   This program is free software; you can redistribute it and/or modify
   it under the terms of the GNU General Public License as published by
   the Free Software Foundation; either version 2 of the License, or
   (at your option) any later version.

   This program is distributed in the hope that it will be useful,
   but WITHOUT ANY WARRANTY; without even the implied warranty of
   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
   GNU General Public License for more details.

   You should have received a copy of the GNU General Public License
   along with this program; if not, write to the Free Software
   Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA
   02110-1301 USA

*/
#include "symbols.h"
#include <assert.h>

UTILLIB_SYMBOL_BEGIN(pascal_symbols)
UTILLIB_SYMBOL_NON_TERMINAL(SYM_PROGRAM)
UTILLIB_SYMBOL_NON_TERMINAL(SYM_SUBPRG)
UTILLIB_SYMBOL_NON_TERMINAL(SYM_CONST_DECL)
UTILLIB_SYMBOL_NON_TERMINAL(SYM_CONST_DEF)
UTILLIB_SYMBOL_NON_TERMINAL(SYM_VAR_DECL)
UTILLIB_SYMBOL_NON_TERMINAL(SYM_PROC_HD)
UTILLIB_SYMBOL_NON_TERMINAL(SYM_STMT)
UTILLIB_SYMBOL_NON_TERMINAL(SYM_ASS_STMT)
UTILLIB_SYMBOL_NON_TERMINAL(SYM_COND_STMT)
UTILLIB_SYMBOL_NON_TERMINAL(SYM_LOOP_STMT)
UTILLIB_SYMBOL_NON_TERMINAL(SYM_CALL_STMT)
UTILLIB_SYMBOL_NON_TERMINAL(SYM_COMP_STMT)
UTILLIB_SYMBOL_NON_TERMINAL(SYM_READ_STMT)
UTILLIB_SYMBOL_NON_TERMINAL(SYM_WRITE_STMT)
UTILLIB_SYMBOL_NON_TERMINAL(SYM_EXPR)
UTILLIB_SYMBOL_NON_TERMINAL(SYM_TERM)
UTILLIB_SYMBOL_NON_TERMINAL(SYM_FACT)
UTILLIB_SYMBOL_NON_TERMINAL(SYM_SIGN)
UTILLIB_SYMBOL_NON_TERMINAL(SYM_ADD_OP)
UTILLIB_SYMBOL_NON_TERMINAL(SYM_MUL_OP)
UTILLIB_SYMBOL_NON_TERMINAL(SYM_TERM_LS)
UTILLIB_SYMBOL_NON_TERMINAL(SYM_COND)
UTILLIB_SYMBOL_NON_TERMINAL(SYM_FACT_LS)
UTILLIB_SYMBOL_NON_TERMINAL(SYM_REL_OP)
UTILLIB_SYMBOL_NON_TERMINAL(SYM_EXPR_LS)
UTILLIB_SYMBOL_NON_TERMINAL(SYM_PROC_DECL)
UTILLIB_SYMBOL_NON_TERMINAL(SYM_CONST_DEF_LS)
UTILLIB_SYMBOL_NON_TERMINAL(SYM_IDEN_LS)
UTILLIB_SYMBOL_NON_TERMINAL(SYM_STMT_LS)
UTILLIB_SYMBOL_NON_TERMINAL(SYM_PROC_DECL_LS)

UTILLIB_SYMBOL_TERMINAL(SYM_KW_PROC)
UTILLIB_SYMBOL_TERMINAL(SYM_KW_ODD)
UTILLIB_SYMBOL_TERMINAL(SYM_KW_READ)
UTILLIB_SYMBOL_TERMINAL(SYM_KW_DO)
UTILLIB_SYMBOL_TERMINAL(SYM_KW_BEGIN)
UTILLIB_SYMBOL_TERMINAL(SYM_KW_END)
UTILLIB_SYMBOL_TERMINAL(SYM_KW_CALL)
UTILLIB_SYMBOL_TERMINAL(SYM_KW_CONST)
UTILLIB_SYMBOL_TERMINAL(SYM_KW_WRITE)
UTILLIB_SYMBOL_TERMINAL(SYM_KW_WHILE)
UTILLIB_SYMBOL_TERMINAL(SYM_KW_THEN)
UTILLIB_SYMBOL_TERMINAL(SYM_KW_IF)
UTILLIB_SYMBOL_TERMINAL(SYM_KW_VAR)
UTILLIB_SYMBOL_TERMINAL(SYM_CEQ)
UTILLIB_SYMBOL_TERMINAL(SYM_ADD)
UTILLIB_SYMBOL_TERMINAL(SYM_MUL)
UTILLIB_SYMBOL_TERMINAL(SYM_NE)
UTILLIB_SYMBOL_TERMINAL(SYM_SEMI)
UTILLIB_SYMBOL_TERMINAL(SYM_IDEN)
UTILLIB_SYMBOL_TERMINAL(SYM_EQ)
UTILLIB_SYMBOL_TERMINAL(SYM_UINT)
UTILLIB_SYMBOL_TERMINAL(SYM_LT)
UTILLIB_SYMBOL_TERMINAL(SYM_LE)
UTILLIB_SYMBOL_TERMINAL(SYM_GT)
UTILLIB_SYMBOL_TERMINAL(SYM_GE)
UTILLIB_SYMBOL_TERMINAL(SYM_DIV)
UTILLIB_SYMBOL_TERMINAL(SYM_MINUS)
UTILLIB_SYMBOL_TERMINAL(SYM_COMMA)
UTILLIB_SYMBOL_TERMINAL(SYM_LP)
UTILLIB_SYMBOL_TERMINAL(SYM_RP)
UTILLIB_SYMBOL_TERMINAL(SYM_DOT)

UTILLIB_SYMBOL_END(pascal_symbols);

const size_t pascal_symbols_size = UTTILLIB_SYMBOL_SIZE(pascal_symbols);

char const *pascal_symbol_kind_tostring(int value) {
  assert(0 < value && value < pascal_symbol_kind_N &&
         "Array index out of range");
  return pascal_symbols[value].name;
}
