/*
   Cmplr Library
   Copyright (C) 2017-2018 Cong Feng <cgsdfc@126.com>

   This program is free software; you can redistribute it and/or modify
   it under the terms of the GNU General Public License as published by
   the Free Software Foundation; either version 2 of the License, or
   (at your option) any later version.

   This program is distributed in the hope that it will be useful,
   but WITHOUT ANY WARRANTY; without even the implied warranty of
   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
   GNU General Public License for more details.

   You should have received a copy of the GNU General Public License
   along with this program; if not, write to the Free Software
   Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA
   02110-1301 USA

*/
#ifndef PASCAL_SYMBOLS_H
#define PASCAL_SYMBOLS_H
#include <utillib/enum.h>
#include <utillib/symbol.h>

UTILLIB_ENUM_BEGIN(pascal_symbol_kind)
UTILLIB_ENUM_ELEM_INIT(SYM_PROGRAM, 1)
UTILLIB_ENUM_ELEM(SYM_SUBPRG)
UTILLIB_ENUM_ELEM(SYM_CONST_DECL)
UTILLIB_ENUM_ELEM(SYM_CONST_DEF)
UTILLIB_ENUM_ELEM(SYM_VAR_DECL)
UTILLIB_ENUM_ELEM(SYM_PROC_HD)
UTILLIB_ENUM_ELEM(SYM_STMT)
UTILLIB_ENUM_ELEM(SYM_ASS_STMT)
UTILLIB_ENUM_ELEM(SYM_COND_STMT)
UTILLIB_ENUM_ELEM(SYM_LOOP_STMT)
UTILLIB_ENUM_ELEM(SYM_CALL_STMT)
UTILLIB_ENUM_ELEM(SYM_COMP_STMT)
UTILLIB_ENUM_ELEM(SYM_READ_STMT)
UTILLIB_ENUM_ELEM(SYM_WRITE_STMT)
UTILLIB_ENUM_ELEM(SYM_EXPR)
UTILLIB_ENUM_ELEM(SYM_TERM)
UTILLIB_ENUM_ELEM(SYM_FACT)
UTILLIB_ENUM_ELEM(SYM_SIGN)
UTILLIB_ENUM_ELEM(SYM_ADD_OP)
UTILLIB_ENUM_ELEM(SYM_MUL_OP)
UTILLIB_ENUM_ELEM(SYM_TERM_LS)
UTILLIB_ENUM_ELEM(SYM_COND)
UTILLIB_ENUM_ELEM(SYM_FACT_LS)
UTILLIB_ENUM_ELEM(SYM_REL_OP)
UTILLIB_ENUM_ELEM(SYM_EXPR_LS)
UTILLIB_ENUM_ELEM(SYM_PROC_DECL)
UTILLIB_ENUM_ELEM(SYM_CONST_DEF_LS)
UTILLIB_ENUM_ELEM(SYM_IDEN_LS)
UTILLIB_ENUM_ELEM(SYM_STMT_LS)
UTILLIB_ENUM_ELEM(SYM_PROC_DECL_LS)

UTILLIB_ENUM_ELEM(SYM_KW_PROC)
UTILLIB_ENUM_ELEM(SYM_KW_ODD)
UTILLIB_ENUM_ELEM(SYM_KW_READ)
UTILLIB_ENUM_ELEM(SYM_KW_DO)
UTILLIB_ENUM_ELEM(SYM_KW_BEGIN)
UTILLIB_ENUM_ELEM(SYM_KW_END)
UTILLIB_ENUM_ELEM(SYM_KW_CALL)
UTILLIB_ENUM_ELEM(SYM_KW_CONST)
UTILLIB_ENUM_ELEM(SYM_KW_WRITE)
UTILLIB_ENUM_ELEM(SYM_KW_WHILE)
UTILLIB_ENUM_ELEM(SYM_KW_THEN)
UTILLIB_ENUM_ELEM(SYM_KW_IF)
UTILLIB_ENUM_ELEM(SYM_KW_VAR)

UTILLIB_ENUM_ELEM(SYM_CEQ)
UTILLIB_ENUM_ELEM(SYM_ADD)
UTILLIB_ENUM_ELEM(SYM_MUL)
UTILLIB_ENUM_ELEM(SYM_NE)
UTILLIB_ENUM_ELEM(SYM_SEMI)
UTILLIB_ENUM_ELEM(SYM_IDEN)
UTILLIB_ENUM_ELEM(SYM_EQ)
UTILLIB_ENUM_ELEM(SYM_UINT)
UTILLIB_ENUM_ELEM(SYM_LT)
UTILLIB_ENUM_ELEM(SYM_LE)
UTILLIB_ENUM_ELEM(SYM_GT)
UTILLIB_ENUM_ELEM(SYM_GE)
UTILLIB_ENUM_ELEM(SYM_DIV)
UTILLIB_ENUM_ELEM(SYM_MINUS)
UTILLIB_ENUM_ELEM(SYM_COMMA)
UTILLIB_ENUM_ELEM(SYM_LP)
UTILLIB_ENUM_ELEM(SYM_RP)
UTILLIB_ENUM_ELEM(SYM_DOT)
UTILLIB_ENUM_END(pascal_symbol_kind);

extern struct utillib_symbol const pascal_symbols[];
extern const size_t pascal_symbols_size;

#endif /* PASCAL_SYMBOLS_H */
