#ifndef SCANNER_ERROR_H
#define SCANNER_ERROR_H
#include "utillib/enum.h"

UTILLIB_ENUM_BEGIN(scanner_error)
  UTILLIB_ENUM_ELEM_INIT(SCANNER_EOF, -1)
  UTILLIB_ENUM_ELEM_INIT(SCANNER_UNMATCHED, -2)
UTILLIB_ENUM_END(scanner_error)

#endif // SCANNER_ERROR_H
